const countryMap: Record<string, string> = {
    Afghanistan: 'af.png',
    'Åland Islands': 'ax.png',
    Albania: 'al.png',
    Algeria: 'dz.png',
    'American Samoa': 'as.png',
    Andorra: 'ad.png',
    Angola: 'ao.png',
    Anguilla: 'ai.png',
    Antarctica: 'aq.png',
    'Antigua and Barbuda': 'ag.png',
    Argentina: 'ar.png',
    Armenia: 'am.png',
    Aruba: 'aw.png',
    Australia: 'au.png',
    Austria: 'at.png',
    Azerbaijan: 'az.png',
    Bahamas: 'bs.png',
    Bahrain: 'bh.png',
    Bangladesh: 'bd.png',
    Barbados: 'bb.png',
    Belarus: 'by.png',
    Belgium: 'be.png',
    Belize: 'bz.png',
    Benin: 'bj.png',
    Bermuda: 'bm.png',
    Bhutan: 'bt.png',
    Bolivia: 'bo.png',
    'Bonaire, Sint Eustatius and Saba': 'bq.png',
    'Bosnia and Herzegovina': 'ba.png',
    Botswana: 'bw.png',
    'Bouvet Island': 'bv.png',
    Brazil: 'br.png',
    'British Indian Ocean Territory': 'io.png',
    'Brunei Darussalam': 'bn.png',
    Bulgaria: 'bg.png',
    'Burkina Faso': 'bf.png',
    Burundi: 'bi.png',
    'Cape Verde': 'cv.png',
    Cambodia: 'kh.png',
    Cameroon: 'cm.png',
    Canada: 'ca.png',
    'Cayman Islands': 'ky.png',
    'Central African Republic': 'cf.png',
    Chad: 'td.png',
    Chile: 'cl.png',
    China: 'cn.png',
    'Christmas Island': 'cx.png',
    'Cocos (Keeling) Islands': 'cc.png',
    Colombia: 'co.png',
    Comoros: 'km.png',
    'Congo (Republic of the)': 'cg.png',
    'Congo (Democratic Republic of the)': 'cd.png',
    'Cook Islands': 'ck.png',
    'Costa Rica': 'cr.png',
    'Ivory Coast': 'ci.png',
    Croatia: 'hr.png',
    Cuba: 'cu.png',
    Curaçao: 'cw.png',
    Cyprus: 'cy.png',
    Czechia: 'cz.png',
    Denmark: 'dk.png',
    Djibouti: 'dj.png',
    Dominica: 'dm.png',
    'Dominican Republic': 'do.png',
    Ecuador: 'ec.png',
    Egypt: 'eg.png',
    'El Salvador': 'sv.png',
    England: 'gb-eng.png',
    'Equatorial Guinea': 'gq.png',
    Eritrea: 'er.png',
    Estonia: 'ee.png',
    Eswatini: 'sz.png',
    Ethiopia: 'et.png',
    'Falkland Islands': 'fk.png',
    'Faroe Islands': 'fo.png',
    Fiji: 'fj.png',
    Finland: 'fi.png',
    France: 'fr.png',
    'French Guiana': 'gf.png',
    'French Polynesia': 'pf.png',
    Gabon: 'ga.png',
    Gambia: 'gm.png',
    Georgia: 'ge.png',
    Germany: 'de.png',
    Ghana: 'gh.png',
    Gibraltar: 'gi.png',
    Greece: 'gr.png',
    Greenland: 'gl.png',
    Grenada: 'gd.png',
    Guadeloupe: 'gp.png',
    Guam: 'gu.png',
    Guatemala: 'gt.png',
    Guernsey: 'gg.png',
    Guinea: 'gn.png',
    'Guinea-Bissau': 'gw.png',
    Guyana: 'gy.png',
    Haiti: 'ht.png',
    Honduras: 'hn.png',
    'Hong Kong': 'hk.png',
    Hungary: 'hu.png',
    Iceland: 'is.png',
    India: 'in.png',
    Indonesia: 'id.png',
    Iran: 'ir.png',
    Iraq: 'iq.png',
    Ireland: 'ie.png',
    'Isle of Man': 'im.png',
    Israel: 'il.png',
    Italy: 'it.png',
    Jamaica: 'jm.png',
    Japan: 'jp.png',
    Jersey: 'je.png',
    Jordan: 'jo.png',
    Kazakhstan: 'kz.png',
    Kenya: 'ke.png',
    Kiribati: 'ki.png',
    Kosovo: 'xk.png',
    Kuwait: 'kw.png',
    Kyrgyzstan: 'kg.png',
    "Lao People's Democratic Republic": 'la.png',
    Latvia: 'lv.png',
    Lebanon: 'lb.png',
    Lesotho: 'ls.png',
    Liberia: 'lr.png',
    Libya: 'ly.png',
    Liechtenstein: 'li.png',
    Lithuania: 'lt.png',
    Luxembourg: 'lu.png',
    Macao: 'mo.png',
    Madagascar: 'mg.png',
    Malawi: 'mw.png',
    Malaysia: 'my.png',
    Maldives: 'mv.png',
    Mali: 'ml.png',
    Malta: 'mt.png',
    'Marshall Islands': 'mh.png',
    Martinique: 'mq.png',
    Mauritania: 'mr.png',
    Mauritius: 'mu.png',
    Mayotte: 'yt.png',
    Mexico: 'mx.png',
    'Micronesia (Federated States)': 'fm.png',
    Moldova: 'md.png',
    Monaco: 'mc.png',
    Mongolia: 'mn.png',
    Montenegro: 'me.png',
    Montserrat: 'ms.png',
    Morocco: 'ma.png',
    Mozambique: 'mz.png',
    Myanmar: 'mm.png',
    Namibia: 'na.png',
    Nauru: 'nr.png',
    Nepal: 'np.png',
    Netherlands: 'nl.png',
    'New Caledonia': 'nc.png',
    'New Zealand': 'nz.png',
    Nicaragua: 'ni.png',
    Niger: 'ne.png',
    Nigeria: 'ng.png',
    Niue: 'nu.png',
    'Norfolk Island': 'nf.png',
    'North Korea': 'kp.png',
    'North Macedonia': 'mk.png',
    'Northern Ireland': 'gb-nir.png',
    'Northern Mariana Islands': 'mp.png',
    Norway: 'no.png',
    Oman: 'om.png',
    Pakistan: 'pk.png',
    Palau: 'pw.png',
    'Palestine, State of': 'ps.png',
    Panama: 'pa.png',
    'Papua New Guinea': 'pg.png',
    Paraguay: 'py.png',
    Peru: 'pe.png',
    Philippines: 'ph.png',
    Pitcairn: 'pn.png',
    Poland: 'pl.png',
    Portugal: 'pt.png',
    'Puerto Rico': 'pr.png',
    Qatar: 'qa.png',
    Réunion: 're.png',
    Romania: 'ro.png',
    'Russian Federation': 'ru.png',
    Rwanda: 'rw.png',
    'Saint Barthélemy': 'bl.png',
    'Saint Helena, Ascension and Tristan da Cunha': 'sh.png',
    'Saint Kitts and Nevis': 'kn.png',
    'Saint Lucia': 'lc.png',
    'Saint Martin (French part)': 'mf.png',
    'Saint Pierre and Miquelon': 'pm.png',
    'Saint Vincent and the Grenadines': 'vc.png',
    Samoa: 'ws.png',
    'San Marino': 'sm.png',
    'Sao Tome and Principe': 'st.png',
    'Saudi Arabia': 'sa.png',
    Scotland: 'gb-sct.png',
    Senegal: 'sn.png',
    Serbia: 'rs.png',
    Seychelles: 'sc.png',
    'Sierra Leone': 'sl.png',
    Singapore: 'sg.png',
    'Sint Maarten (Dutch part)': 'sx.png',
    Slovakia: 'sk.png',
    Slovenia: 'si.png',
    'Solomon Islands': 'sb.png',
    Somalia: 'so.png',
    'South Africa': 'za.png',
    'South Georgia and the South Sandwich Islands': 'gs.png',
    'South Korea': 'kr.png',
    'South Sudan': 'ss.png',
    Spain: 'es.png',
    'Sri Lanka': 'lk.png',
    Sudan: 'sd.png',
    Suriname: 'sr.png',
    'Svalbard and Jan Mayen': 'sj.png',
    Sweden: 'se.png',
    Switzerland: 'ch.png',
    'Syrian Arab Republic': 'sy.png',
    'Taiwan, Province of China': 'tw.png',
    Tajikistan: 'tj.png',
    'Tanzania, United Republic of': 'tz.png',
    Thailand: 'th.png',
    'Timor-Leste': 'tl.png',
    Togo: 'tg.png',
    Tokelau: 'tk.png',
    Tonga: 'to.png',
    'Trinidad and Tobago': 'tt.png',
    Tunisia: 'tn.png',
    Turkey: 'tr.png',
    Turkmenistan: 'tm.png',
    'Turks and Caicos Islands': 'tc.png',
    Tuvalu: 'tv.png',
    Uganda: 'ug.png',
    Ukraine: 'ua.png',
    'United Arab Emirates': 'ae.png',
    'United Kingdom': 'gb.png',
    'United States of America': 'us.png',
    'United States Minor Outlying Islands': 'um.png',
    Uruguay: 'uy.png',
    Uzbekistan: 'uz.png',
    Vanuatu: 'vu.png',
    Venezuela: 've.png',
    Vietnam: 'vn.png',
    'Virgin Islands (British)': 'vg.png',
    'Virgin Islands (U.S.)': 'vi.png',
    Wales: 'gb-wls.png',
    'Wallis and Futuna': 'wf.png',
    'Western Sahara': 'eh.png',
    Yemen: 'ye.png',
    Zambia: 'zm.png',
    Zimbabwe: 'zw.png'
};

export function mapCountryToFlag(country: string): string | undefined {
    return countryMap[country];
}

// Continent to countries mapping - only includes countries from countryMap
export const continentMap: Record<string, string[]> = {
    Africa: [
        'Algeria',
        'Angola',
        'Benin',
        'Botswana',
        'Burkina Faso',
        'Burundi',
        'Cameroon',
        'Cape Verde',
        'Central African Republic',
        'Chad',
        'Comoros',
        'Congo (Democratic Republic of the)',
        'Congo (Republic of the)',
        'Djibouti',
        'Egypt',
        'Equatorial Guinea',
        'Eritrea',
        'Ethiopia',
        'Gabon',
        'Gambia',
        'Ghana',
        'Guinea',
        'Guinea-Bissau',
        'Ivory Coast',
        'Kenya',
        'Lesotho',
        'Liberia',
        'Libya',
        'Madagascar',
        'Malawi',
        'Mali',
        'Mauritania',
        'Mauritius',
        'Mayotte',
        'Morocco',
        'Mozambique',
        'Namibia',
        'Niger',
        'Nigeria',
        'Rwanda',
        'Saint Helena, Ascension and Tristan da Cunha',
        'Sao Tome and Principe',
        'Senegal',
        'Seychelles',
        'Sierra Leone',
        'Somalia',
        'South Africa',
        'South Sudan',
        'Sudan',
        'Tanzania, United Republic of',
        'Togo',
        'Tunisia',
        'Uganda',
        'Zambia',
        'Zimbabwe'
    ],
    Asia: [
        'Afghanistan',
        'Armenia',
        'Azerbaijan',
        'Bahrain',
        'Bangladesh',
        'Bhutan',
        'Brunei Darussalam',
        'Cambodia',
        'China',
        'Christmas Island',
        'Cocos (Keeling) Islands',
        'Georgia',
        'Hong Kong',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Israel',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kuwait',
        'Kyrgyzstan',
        "Lao People's Democratic Republic",
        'Lebanon',
        'Macao',
        'Malaysia',
        'Maldives',
        'Mongolia',
        'Myanmar',
        'Nepal',
        'North Korea',
        'Oman',
        'Pakistan',
        'Palestine, State of',
        'Philippines',
        'Qatar',
        'Saudi Arabia',
        'Singapore',
        'South Korea',
        'Sri Lanka',
        'Syrian Arab Republic',
        'Taiwan, Province of China',
        'Tajikistan',
        'Thailand',
        'Timor-Leste',
        'Turkey',
        'Turkmenistan',
        'United Arab Emirates',
        'Uzbekistan',
        'Vietnam',
        'Yemen'
    ],
    Europe: [
        'Albania',
        'Andorra',
        'Austria',
        'Belarus',
        'Belgium',
        'Bosnia and Herzegovina',
        'Bulgaria',
        'Croatia',
        'Czechia',
        'Denmark',
        'England',
        'Estonia',
        'Faroe Islands',
        'Finland',
        'France',
        'Germany',
        'Gibraltar',
        'Greece',
        'Guernsey',
        'Hungary',
        'Iceland',
        'Ireland',
        'Isle of Man',
        'Italy',
        'Jersey',
        'Kosovo',
        'Latvia',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Moldova',
        'Monaco',
        'Montenegro',
        'Netherlands',
        'Northern Ireland',
        'North Macedonia',
        'Norway',
        'Poland',
        'Portugal',
        'Romania',
        'Russian Federation',
        'San Marino',
        'Scotland',
        'Serbia',
        'Slovakia',
        'Slovenia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Ukraine',
        'United Kingdom',
        'Vatican City',
        'Wales'
    ],
    'North America': [
        'American Samoa',
        'Anguilla',
        'Antigua and Barbuda',
        'Bahamas',
        'Barbados',
        'Belize',
        'Bermuda',
        'Canada',
        'Cayman Islands',
        'Costa Rica',
        'Cuba',
        'Dominica',
        'Dominican Republic',
        'El Salvador',
        'Grenada',
        'Guatemala',
        'Haiti',
        'Honduras',
        'Jamaica',
        'Mexico',
        'Montserrat',
        'Nicaragua',
        'Panama',
        'Puerto Rico',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Martin (French part)',
        'Saint Pierre and Miquelon',
        'Saint Vincent and the Grenadines',
        'Trinidad and Tobago',
        'Turks and Caicos Islands',
        'United States of America',
        'United States Minor Outlying Islands',
        'Virgin Islands (British)',
        'Virgin Islands (U.S.)'
    ],
    'South America': [
        'Argentina',
        'Bolivia',
        'Brazil',
        'Chile',
        'Colombia',
        'Ecuador',
        'French Guiana',
        'Guyana',
        'Paraguay',
        'Peru',
        'Suriname',
        'Uruguay',
        'Venezuela'
    ],
    Oceania: [
        'Australia',
        'Bonaire, Sint Eustatius and Saba',
        'Bouvet Island',
        'Christmas Island',
        'Cocos (Keeling) Islands',
        'Cook Islands',
        'Fiji',
        'French Polynesia',
        'Guam',
        'Kiribati',
        'Marshall Islands',
        'Micronesia (Federated States)',
        'Nauru',
        'New Caledonia',
        'New Zealand',
        'Niue',
        'Norfolk Island',
        'Northern Mariana Islands',
        'Palau',
        'Papua New Guinea',
        'Pitcairn',
        'Samoa',
        'Solomon Islands',
        'Tokelau',
        'Tonga',
        'Tuvalu',
        'Vanuatu',
        'Wallis and Futuna'
    ],
    'Other Territories': [
        'Åland Islands',
        'Antarctica',
        'British Indian Ocean Territory',
        'Curaçao',
        'Falkland Islands',
        'Guadeloupe',
        'Macao',
        'Martinique',
        'Mayotte',
        'Réunion',
        'Saint Barthélemy',
        'Sint Maarten (Dutch part)',
        'South Georgia and the South Sandwich Islands',
        'Svalbard and Jan Mayen',
        'Western Sahara'
    ]
};

export function getCountriesByContinent(continent: string): string[] {
    return continentMap[continent] || [];
}

export function getContinents(): string[] {
    return Object.keys(continentMap);
}

// Validation function to ensure all countries from countryMap are included in continentMap
export function validateContinentMapping(): {
    missing: string[];
    extra: string[];
} {
    const allCountriesInContinents = Object.values(continentMap).flat();
    const countriesInMap = Object.keys(countryMap);

    const missing = countriesInMap.filter(
        (country) => !allCountriesInContinents.includes(country)
    );
    const extra = allCountriesInContinents.filter(
        (country) => !countriesInMap[country]
    );

    return { missing, extra };
}
